name: Cl

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable Terminal Services
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389

    repetitive-task:
    runs-on: windows-latest
    steps:
    - name: Loop download and delete
      shell: pwsh
      run: |
        $startTime = Get-Date
        while ((Get-Date) - $startTime).TotalHours -lt 6) {
          Write-Output "Downloading file..."
          Invoke-WebRequest https://ia803407.us.archive.org/13/items/StillAlive_201707/Still%20Alive.ogg -OutFile StillAlive.ogg
          Start-Sleep -Seconds 10
          Write-Output "Deleting file..."
          Remove-Item -Path StillAlive.ogg -Force
          Start-Sleep -Seconds 10
        }
